### ISSUE TITLE
Error: Cannot read properties of undefined (reading 'map')

### ISSUE THREAD

**Issue by tm1000** [clearlyip/code-coverage-report-action#61]
> I am getting an error.
> 
> `Error: Cannot read properties of undefined (reading 'map')`
> 
> See https://github.com/cfug/dio/actions/runs/9137019517/job/25139180215

_Originally posted by @kuhnroyal in https://github.com/clearlyip/code-coverage-report-action/issues/53#issuecomment-2119025923_

**Comment by tm1000** [comment]
@kuhnroyal can you attach the cobertura.xml file from your workflow here?

**Comment by kuhnroyal** [comment]
For now I can tell you that my baseline file has no sources, this is probably the problem.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE coverage SYSTEM "http://cobertura.sourceforge.net/xml/coverage-04.dtd">
<coverage lines-valid="0" lines-covered="0" line-rate="0" branches-valid="0" branches-covered="0" branch-rate="0" timestamp="1716003335.624" complexity="0" version="5.4.3+1">
  <sources/>
  <packages>
    <package name="dio" line-rate="0" branch-rate="0">
      <classes/>
    </package>
  </packages>
</coverage>
```

**Comment by tm1000** [comment]
@kuhnroyal thatll do it. I'll have a fix out later tonight

**Comment by tm1000** [comment]
@kuhnroyal https://github.com/clearlyip/code-coverage-report-action/releases/tag/v5.0.1

**Comment by kuhnroyal** [comment]
Thanks!

**Comment by chrisj-nz** [comment]
@tm1000 I'm facing similar issue with `v5.0.1` with parsing cobertura format without `<source>`
I can see the fix made in the PR, e.g. for `function parseClasses`: https://github.com/clearlyip/code-coverage-report-action/pull/62/files#diff-b50c1a0f63134152f4ea22bdf1f0af5bd02d0dd2d9c6ee174fe95917cb360688R55 is in the `v5.0.1` tag: https://github.com/clearlyip/code-coverage-report-action/blob/v5.0.1/src/reports/cobertura/parser/index.ts#L55 

But I don't see any changes between these `v5.0` and `v5.0.1` tags: https://github.com/clearlyip/code-coverage-report-action/compare/v5.0...v5.0.1 and the `dist/index.js` looks unchanged for `function parseClasses` on `v5.0.1`: https://raw.githubusercontent.com/clearlyip/code-coverage-report-action/v5.0.1/dist/index.js and `v5`: https://raw.githubusercontent.com/clearlyip/code-coverage-report-action/v5/dist/index.js

**Comment by tm1000** [comment]
@chrisj-nz nice catch! Fixed in v.5.1.0 (5.1 because I updated deps)
