### ISSUE TITLE
Cannot read properties of undefined (reading 'Symbol(Symbol.asyncIterator)')

### ISSUE THREAD

**Issue by gregorio-gerardi** [clearlyip/code-coverage-report-action#82]
Hi! I am facing an issue when the cobertura file that I am trying to process has no coverage info

Example: 
```
<?xml version="1.0" ?>
<!DOCTYPE coverage SYSTEM "http://cobertura.sourceforge.net/xml/coverage-04.dtd">
<coverage lines-valid="0" lines-covered="0" line-rate="NaN" branches-valid="0" branches-covered="0" branch-rate="NaN" timestamp="1726170429312" complexity="0" version="0.1">
  <sources>
    <source>/Users/gregoriogerardi/Documents/dashjs</source>
  </sources>
  <packages>
  </packages>
</coverage>
```

This is being generated by [jest](https://jestjs.io/) like

`
jest --collectCoverage=true '--coverageReporters="cobertura"' --changedSince <some-commit-hash-here>
`

This "empty" file is expected when running this action for PRs that do not change tested files (like readme updates).

**Comment by tm1000** [comment]
Are you using version 5.x? 

See: https://github.com/clearlyip/code-coverage-report-action/issues/67

**Comment by gregorio-gerardi** [comment]
> Are you using version 5.x?
> 
> See: #67

@tm1000 yes, I am on 5.1. From a (quick and probably incorrect) look at the code, maybe this is where the issue is based on the XML I am trying to parse 

https://github.com/embrace-io/code-coverage-report-action/blob/main/src/reports/cobertura/parser/index.ts#L38

called from https://github.com/embrace-io/code-coverage-report-action/blob/main/src/reports/cobertura/parser/index.ts#L11

If you check the XML I attached, `cobertura.coverage.packages.package` is undefined. 

I can attempt to submit a PR tomorrow if that helps, it does not sound like the most complex of the issues If my guess is correct 🙂 and according to the [cobertura spec](https://github.com/cobertura/web/blob/5ade495c8f8f5308490bdfbbbe61aafe25a1b67b/htdocs/xml/coverage-04.dtd#L22) and empty `packages` should be supported
